apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: 192.168.1.10:5000/library/email-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MONGO_DB_NAME
              value: "email_service"
            - name: MONGO_URI
              value: "mongodb://root:pass@192.168.1.10:27017/email_service?authSource=admin&retryWrites=true&w=majority"
            - name: SQS_QUEUE
              value: "email-queue"
            - name: AWS_ENDPOINT_URL
              value: "http://192.168.1.10:4566"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY
              value: "test"
            - name: AWS_SECRET_KEY
              value: "test"
              
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3